### ISSUE TITLE
Dependency issue with System.Drawing.Common 5.0.2

### ISSUE THREAD

**Issue by KyuubiYoru** [Sharp0802/WebP.Net#1]
I've been trying to use your NuGet package, but I ran into an issue with one of its dependencies. 
The System.Drawing.Common 5.0.2 NuGet package has been flagged with a critical security vulnerability on NuGet.
This issue prevents the installation of your package.

https://www.nuget.org/packages/System.Drawing.Common/5.0.2

**Comment by Sharp0802** [comment]
Sorry for not contacting you sooner.

The package reference(`System.Drawing.Common`) has been updated to latest stable version(7.0.0),
and new version 1.1.1 have been deployed to nuget.

https://www.nuget.org/packages/WebP_Net/1.1.1

If you are still experiencing the same issue with version 1.1.1,
Please create new issue about it.
